### ISSUE TITLE
Password authentication failed

### ISSUE THREAD

**Issue by Crocmagnon** [nextcloud/notify_push#10]
I'm trying to run notify_push in a separate docker container, sharing the volume of the "real" nextcloud but I'm getting an obscure error: `Password authentication failed`.

Here are the logs:
```
notify_push_1  | 2021-02-22T16:59:18.055940082Z Error:
notify_push_1  | 2021-02-22T16:59:18.055975911Z    0: Password authentication failed
notify_push_1  | 2021-02-22T16:59:18.055979397Z
notify_push_1  | 2021-02-22T16:59:18.055981922Z Location:
notify_push_1  | 2021-02-22T16:59:18.055984316Z    /tmp/krankerl.V81FqtLwaNcP/notify_push/src/lib.rs:108
notify_push_1  | 2021-02-22T16:59:18.055988163Z
notify_push_1  | 2021-02-22T16:59:18.055990919Z   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
notify_push_1  | 2021-02-22T16:59:18.055995668Z    1: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::ha0376ab6d5c47fdb
notify_push_1  | 2021-02-22T16:59:18.055999284Z       at <unknown source file>:<unknown line>
notify_push_1  | 2021-02-22T16:59:18.056003091Z    2: notify_push::main::{{closure}}::h8353892e3b19db59
notify_push_1  | 2021-02-22T16:59:18.056006789Z       at <unknown source file>:<unknown line>
notify_push_1  | 2021-02-22T16:59:18.056010355Z    3: notify_push::main::h4f6958ef3c78b4fd
notify_push_1  | 2021-02-22T16:59:18.056015625Z       at <unknown source file>:<unknown line>
notify_push_1  | 2021-02-22T16:59:18.056019462Z    4: std::sys_common::backtrace::__rust_begin_short_backtrace::h35bee24ae9e94d86
notify_push_1  | 2021-02-22T16:59:18.056022728Z       at <unknown source file>:<unknown line>
notify_push_1  | 2021-02-22T16:59:18.056025694Z    5: main<unknown>
notify_push_1  | 2021-02-22T16:59:18.056028109Z       at <unknown source file>:<unknown line>
notify_push_1  | 2021-02-22T16:59:18.056030524Z
notify_push_1  | 2021-02-22T16:59:18.056032688Z Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
nextcloud_notify_push_1 exited with code 1
```

Here's my docker-compose config:
```yaml
version: "2.4"
services:
  nextcloud:
    image: nextcloud:21.0.0-apache
    restart: always
    networks:
      - default
      - nginx-proxy-manager_default
    volumes:
      - ./nextcloud_data:/var/www/html
    env_file: nextcloud.env
    depends_on:
      - db
      - redis
  notify_push:
    image: nextcloud:21.0.0-apache
    command: /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html:ro
    env_file: nextcloud.env
    environment:
      RUST_BACKTRACE: full
      COLORBT_SHOW_HIDDEN: 1
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    restart: always
    env_file: postgres.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    restart: always


networks:
  nginx-proxy-manager_default:
    external: true
```

To what does the service try to connect to? Is it redis? At this point I can only guess :/
Here's the relevant config from nextcloud:
```php
  'redis' =>
  array (
    'host' => 'redis',
    'password' => '',
    'port' => 6379,
  ),
  ```
