### ISSUE TITLE
Push server (version 0.1.7) is not the same version as the app (version 0.2.0)

### ISSUE THREAD

**Issue by mgscreativa** [nextcloud/notify_push#104]
HI! I'm trying to deploy the Notifications Server using my current setup:

* Docker through docker-compose
* Apache as proxy

So far, I'm able to try ./occ notify_push:setup, but the command complains about the push server version not equals the client app version

www-data@b424bffc329c:~/html$ ./occ notify_push:setup http://domain.tld.com:7867
✓ redis is configured
x using unencrypted https for push server is strongly discouraged
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
**x push server (version 0.1.7) is not the same version as the app (version 0.2.0).**

Is there a way to solve this version mismatch?

Herre is my **docker-compose.yml** file and the **Apache proxy** config

**docker-compose.yml**
```
version: '2'

services:
  redis:
    image: 'redis:alpine'
    restart: always
    container_name: nextcloud-redis
    volumes:
      - /media/data/nextcloud/redis-data:/data

  app:
    image: 'nextcloud:21.0.2-fpm'
    restart: always
    container_name: nextcloud
    volumes:
      - /media/data/nextcloud/data/html:/var/www/html
      - /media/data/nextcloud/data/config:/var/www/html/config
      - /media/data/nextcloud/data/cloud_data:/var/www/html/data
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      
  notify_push:
    image: nextcloud:21.0.2-fpm
    restart: always
    container_name: nextcloud-notify-push
    ports:
      - 7867:7867
    environment:
      - PORT=7867
      - NEXTCLOUD_URL=https://domain.tld.com/
    volumes:
      - /media/data/nextcloud/data/html:/var/www/html
      - /media/data/nextcloud/data/config:/var/www/html/config:ro
      - /media/data/nextcloud/data/cloud_data:/var/www/html/data
    entrypoint: /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push /var/www/html/config/config.php

  web:
    image: 'nginx'
    restart: always
    container_name: nextcloud-nginx
    ports:
      - 3080:80
    links:
      - app
    volumes:
      - /media/data/nextcloud/data/html:/var/www/html
      - /media/data/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
```

**Apache proxy config**

```
<Proxy />
  Order deny,allow
  Allow from all
</Proxy>

ProxyPreserveHost On
ProxyPass /.well-known/acme-challenge/ !
ProxyPass / http://domain.tld.com:3080/
ProxyPassReverse / http://domain.tld.com:3080/

ProxyPass /push/ws ws://domain.tld.com:7867/ws
ProxyPass /push/ http://domain.tld.com:7867/
ProxyPassReverse /push/ http://domain.tld.com:7867/

ProxyTimeout 21600
```
