### ISSUE TITLE
Unrecognized Database URL when using the docker image

### ISSUE THREAD

**Issue by S0ulf3re** [nextcloud/notify_push#404]
I'm trying to use the notify_push image with my Nextcloud docker instance running on MariaDB. But when I set `DATABASE_URL` as using MariaDB, I just get an error about an unrecognized database URL. This is my config:

```
  notify_push:
    image: docker.io/icewind1991/notify_push
    container_name: notify_push
    networks:
      - mariadb
      - redis
      - nextcloud
    environment:
      - NEXTCLOUD_URL="https://nextcloud/"
      - REDIS_URL="redis://redis"
      - DATABASE_URL="mariadb://nextcloud:${NEXTCLOUD_MYSQL_PASSWORD}@db/nextcloud"
    depends_on:
      - db
      - redis
      - nextcloud
```

I've tried replacing the URI Scheme with `mysql` as well, but that didn't work either.
